// <auto-generated />
using CRUD_ASP.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUD_ASP.Entities
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240213195851_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("CRUD_ASP.Entities.TblBarang", b =>
                {
                    b.Property<int>("IdBarang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id_barang");

                    b.Property<string>("KategoriBarang")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("kategori_barang");

                    b.Property<string>("KeteranganBarang")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("keterangan_barang");

                    b.Property<string>("NamaBarang")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nama_barang");

                    b.HasKey("IdBarang")
                        .HasName("PRIMARY");

                    b.ToTable("tbl_barang", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
